#!/usr/bin/env bash
# scripts/install-deploy-daemon.sh — one-shot installer for the pull-based
# deploy daemon described in issue #107.
#
# Usage (as root, from a clone at REPO_DIR — usually /opt/ai-dev-team):
#   sudo REPO_DIR=/opt/ai-dev-team SLACK_WEBHOOK_URL=https://hooks... \
#        scripts/install-deploy-daemon.sh
#
# Idempotent: re-running with different env values rewrites the env file
# and re-enables the units. Existing /etc/ai-dev-team-deploy.env values
# are preserved unless the env var is explicitly set in the invoking
# environment (so re-running without SLACK_WEBHOOK_URL does NOT wipe it).
set -euo pipefail

REPO_DIR="${REPO_DIR:-/opt/ai-dev-team}"
ENV_FILE="/etc/ai-dev-team-deploy.env"
SYSTEMD_DIR="/etc/systemd/system"
UNIT_SRC="${REPO_DIR}/systemd"

if [ "$(id -u)" -ne 0 ]; then
    echo "This installer must run as root (uses /etc/systemd/system, /etc/ai-dev-team-deploy.env)." >&2
    exit 1
fi

if [ ! -d "$REPO_DIR" ]; then
    echo "REPO_DIR=$REPO_DIR does not exist. Clone the repo there first." >&2
    exit 1
fi

if [ ! -f "$UNIT_SRC/ai-dev-team-deploy.service" ] || [ ! -f "$UNIT_SRC/ai-dev-team-deploy.timer" ]; then
    echo "Expected systemd units at $UNIT_SRC; refusing to continue." >&2
    exit 1
fi

if [ ! -x "$REPO_DIR/scripts/deploy-pull.sh" ]; then
    echo "scripts/deploy-pull.sh is not executable. Fix with: chmod +x scripts/deploy-pull.sh" >&2
    exit 1
fi

# --- Build /etc/ai-dev-team-deploy.env from current env, preserving any
# values already on disk that the caller didn't override. -------------
declare -A CFG
# Defaults — match what scripts/deploy-pull.sh would use internally.
CFG[REPO_DIR]="$REPO_DIR"
CFG[BRANCH]="main"
CFG[HEALTH_URL]="http://localhost:8080/healthz"
CFG[HEALTH_RETRIES]="12"
CFG[HEALTH_INTERVAL]="5"
CFG[SLACK_WEBHOOK_URL]=""

# Load existing file values first (so we don't wipe them on a no-arg re-run).
if [ -f "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    while IFS='=' read -r k v; do
        [ -z "$k" ] && continue
        case "$k" in \#*) continue ;; esac
        # Strip surrounding quotes (if any) — systemd doesn't require them
        # but operators sometimes add them.
        v="${v%\"}"; v="${v#\"}"
        CFG["$k"]="$v"
    done < "$ENV_FILE"
fi

# Anything explicitly set in the calling env wins.
for var in REPO_DIR BRANCH HEALTH_URL HEALTH_RETRIES HEALTH_INTERVAL SLACK_WEBHOOK_URL; do
    if [ -n "${!var-}" ]; then
        CFG["$var"]="${!var}"
    fi
done

umask 077
tmp_env="$(mktemp)"
{
    echo "# Generated by scripts/install-deploy-daemon.sh — see issue #107."
    echo "# Edit in place to tune the daemon, then: systemctl restart ai-dev-team-deploy.timer"
    echo "REPO_DIR=${CFG[REPO_DIR]}"
    echo "BRANCH=${CFG[BRANCH]}"
    echo "HEALTH_URL=${CFG[HEALTH_URL]}"
    echo "HEALTH_RETRIES=${CFG[HEALTH_RETRIES]}"
    echo "HEALTH_INTERVAL=${CFG[HEALTH_INTERVAL]}"
    echo "SLACK_WEBHOOK_URL=${CFG[SLACK_WEBHOOK_URL]}"
} > "$tmp_env"
install -o root -g root -m 600 "$tmp_env" "$ENV_FILE"
rm -f "$tmp_env"
echo "Wrote $ENV_FILE (mode 600, root:root)"

# --- Install/refresh the systemd units --------------------------------
install -o root -g root -m 644 "$UNIT_SRC/ai-dev-team-deploy.service" "$SYSTEMD_DIR/ai-dev-team-deploy.service"
install -o root -g root -m 644 "$UNIT_SRC/ai-dev-team-deploy.timer"   "$SYSTEMD_DIR/ai-dev-team-deploy.timer"
echo "Installed unit files to $SYSTEMD_DIR/"

systemctl daemon-reload
systemctl enable --now ai-dev-team-deploy.timer

echo
echo "ai-dev-team-deploy.timer is enabled and active."
systemctl --no-pager list-timers ai-dev-team-deploy.timer || true
echo
echo "Auto-revert is enabled. If a deploy fails its health check, the"
echo "daemon will revert to the previous SHA. To disable, set"
echo "HEALTH_RETRIES=0 in $ENV_FILE."
echo
echo "Tail the deploy log with:  journalctl -u ai-dev-team-deploy.service -f"
