"""Render ``docker-compose.yml`` from per-agent ``agent.yaml`` manifests.

The router service is fixed; per-agent services and the volumes / depends_on /
env-var lists are generated from the agents discovered under
``config/agents/*/agent.yaml``.

Usage:
    python -m scripts.render_compose                 # write docker-compose.yml
    python -m scripts.render_compose --check         # exit non-zero if stale
    python -m scripts.render_compose -o /tmp/foo.yml # write somewhere else

Default behaviour (no override Dockerfile present):
    services.<name>.image:   ai-dev-team-base:latest
    services.<name>.command: ["sleep", "infinity"]

Override: drop a ``Dockerfile`` next to the agent's manifest at
``config/agents/<name>/Dockerfile`` and the renderer switches that service
to ``build:`` instead.

Hand-edits go in ``docker-compose.override.yml`` (Compose's native escape
hatch); the renderer never touches it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from router.config import discover_agents

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "docker-compose.yml"
DEFAULT_AGENTS_DIR = REPO_ROOT / "config" / "agents"

HEADER = """\
# This file is GENERATED by scripts/render_compose.py from
# config/agents/*/agent.yaml manifests. Do not edit by hand — your changes
# will be overwritten the next time the renderer runs.
#
# Local-only tweaks should go in docker-compose.override.yml (Compose's
# native escape hatch), which the renderer never touches.

"""


def build_compose(agents: dict[str, dict], agents_dir: Path) -> dict:
    """Return the full docker-compose dict for the given agents."""
    sorted_names = sorted(agents.keys())

    services: dict[str, dict] = {"router": _router_service(sorted_names)}
    for name in sorted_names:
        services[name] = _agent_service(name, agents[name], agents_dir)

    volumes: dict[str, None] = {f"{name}-claude-config": None for name in sorted_names}

    return {"services": services, "volumes": volumes}


def _router_service(agent_names: list[str]) -> dict:
    env: list[str] = []
    for name in agent_names:
        prefix = name.upper()
        env.append(f"{prefix}_BOT_TOKEN=${{{prefix}_BOT_TOKEN}}")
        env.append(f"{prefix}_APP_TOKEN=${{{prefix}_APP_TOKEN}}")
        env.append(f"{prefix}_SIGNING_SECRET=${{{prefix}_SIGNING_SECRET}}")
    env.append("SESSION_TIMEOUT=${SESSION_TIMEOUT:-600}")
    env.append("LOG_LEVEL=${LOG_LEVEL:-DEBUG}")

    return {
        "build": {"context": ".", "dockerfile": "router/Dockerfile"},
        "environment": env,
        "volumes": [
            "/var/run/docker.sock:/var/run/docker.sock",
            "./config:/config",
            "./systems:/systems",
        ],
        "deploy": {"resources": {"limits": {"memory": "256m"}}},
        "depends_on": list(agent_names),
        "restart": "unless-stopped",
    }


def _agent_service(name: str, manifest: dict, agents_dir: Path) -> dict:
    container = manifest.get("container", name)
    override_dockerfile = agents_dir / name / "Dockerfile"

    service: dict = {
        "container_name": container,
        "environment": ["CLAUDE_CODE_DISABLE_AUTO_MEMORY=1"],
        "volumes": [
            "./config:/config",
            "./systems:/systems",
            f"{name}-claude-config:/home/claude/.claude",
        ],
        "deploy": {"resources": {"limits": {"memory": "512m"}}},
        "restart": "unless-stopped",
    }

    if override_dockerfile.exists():
        try:
            dockerfile_rel = str(override_dockerfile.relative_to(REPO_ROOT))
        except ValueError:
            dockerfile_rel = str(override_dockerfile)
        service["build"] = {"context": ".", "dockerfile": dockerfile_rel}
    else:
        service["image"] = "ai-dev-team-base:latest"
        service["command"] = ["sleep", "infinity"]

    return service


def render(agents_dir: Path | None = None) -> str:
    """Return the rendered compose YAML (header + body)."""
    base = agents_dir if agents_dir is not None else DEFAULT_AGENTS_DIR
    agents = discover_agents(base)
    compose = build_compose(agents, base)
    body = yaml.safe_dump(compose, sort_keys=False, default_flow_style=False)
    return HEADER + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render docker-compose.yml from agent manifests.")
    parser.add_argument("--output", "-o", default=str(DEFAULT_OUTPUT), help="output path")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the file is stale")
    parser.add_argument(
        "--agents-dir",
        type=Path,
        default=None,
        help="agents dir to discover from (defaults to config/agents)",
    )
    args = parser.parse_args(argv)

    rendered = render(args.agents_dir)
    output_path = Path(args.output)

    if args.check:
        existing = output_path.read_text() if output_path.exists() else ""
        if existing != rendered:
            print(
                f"{output_path} is stale. Run 'python -m scripts.render_compose' to regenerate.",
                file=sys.stderr,
            )
            return 1
        print(f"{output_path} is up to date.")
        return 0

    output_path.write_text(rendered)
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
