"""Render ``docker-compose.yml`` from per-agent ``agent.yaml`` manifests.

The router service is fixed; per-agent services and the volumes / depends_on /
env-var lists are generated from the agents discovered under
``config/agents/*/agent.yaml``.

Usage:
    python -m scripts.render_compose                 # write docker-compose.yml
    python -m scripts.render_compose --check         # exit non-zero if stale
    python -m scripts.render_compose -o /tmp/foo.yml # write somewhere else

Default behaviour (no override Dockerfile present):
    services.<name>.image:   ai-dev-team-base:latest
    services.<name>.command: ["sleep", "infinity"]

Override: drop a ``Dockerfile`` next to the agent's manifest at
``config/agents/<name>/Dockerfile`` and the renderer switches that service
to ``build:`` instead.

Hand-edits go in ``docker-compose.override.yml`` (Compose's native escape
hatch); the renderer never touches it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from router.config import discover_agents

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "docker-compose.yml"
DEFAULT_AGENTS_DIR = REPO_ROOT / "config" / "agents"

HEADER = """\
# This file is GENERATED by scripts/render_compose.py from
# config/agents/*/agent.yaml manifests. Do not edit by hand — your changes
# will be overwritten the next time the renderer runs.
#
# Local-only tweaks should go in docker-compose.override.yml (Compose's
# native escape hatch), which the renderer never touches.

"""


def build_compose(agents: dict[str, dict], agents_dir: Path) -> dict:
    """Return the full docker-compose dict for the given agents."""
    sorted_names = sorted(agents.keys())

    services: dict[str, dict] = {"router": _router_service(sorted_names)}
    for name in sorted_names:
        services[name] = _agent_service(name, agents[name], agents_dir)

    # Opt-in browser_use sidecar. Gated by the ``browser`` compose
    # profile so default ``docker compose up`` skips it — the image is
    # heavy (Chromium + deps) and most agents don't need it.
    #
    # Hardcoded for now rather than discovered from pack manifests:
    # only one pack needs a sidecar today and the wiring (keyfile mount,
    # tmpfs, port, memory ceiling) isn't generic. When a second pack
    # asks for one we'll factor a ``packs/*/sidecar.yaml`` schema; see
    # the PR review thread on #113 for context.
    services["browser-use"] = _browser_use_sidecar()

    volumes: dict[str, None] = {f"{name}-claude-config": None for name in sorted_names}
    # Shared volume for on-demand CLI binaries (gh, fly, …) installed via
    # scripts/install_cli.sh. Mounted into every agent at /opt/tools so new
    # tools become available without rebuilding the base image.
    volumes["agent-tools"] = None

    return {"services": services, "volumes": volumes, "secrets": _secrets_block()}


def _secrets_block() -> dict:
    """Top-level ``secrets:`` block. Currently only the browser_use age keyfile.

    ``AGE_KEYFILE`` is the same env var the bootstrap script honours, so a
    one-shot override (``AGE_KEYFILE=~/.config/ai-dev-team/age.key``) flows
    through both bootstrap and compose without divergence. Default
    ``/etc/ai-dev-team/age.key`` matches a Linux prod host; macOS dev needs
    a path under ``~`` because Docker Desktop's file sharing excludes
    ``/etc`` by default — see ``packs/browser_use/README.md``.
    """
    return {
        "age_key": {"file": "${AGE_KEYFILE:-/etc/ai-dev-team/age.key}"},
    }


def _browser_use_sidecar() -> dict:
    """Compose entry for the browser_use sidecar.

    Mounts:
    - ``./config/browser_profiles`` rw — persistent per-identity Chromium
      profile dirs. Survives sidecar restarts so logins stick.
    - ``./config/secrets/browser`` ro — age-encrypted secret bundle.
      Decrypted in memory at session start; never written to disk in
      plaintext.
    - The host age keyfile arrives via the top-level ``secrets:`` block
      and lands at ``/run/secrets/age.key`` inside the container. Host
      path is ``${AGE_KEYFILE:-/etc/ai-dev-team/age.key}`` — same env
      var the bootstrap script reads.

    Network: the sidecar listens on the docker network only — no host
    port binding. The pack handler reaches it at ``http://browser-use:8080``.
    """
    return {
        "container_name": "browser-use",
        "profiles": ["browser"],
        "build": {"context": ".", "dockerfile": "docker/Dockerfile.browser"},
        "environment": [
            "BROWSER_USE_PROFILES_DIR=/config/browser_profiles",
            "BROWSER_USE_SECRETS_DIR=/config/secrets/browser",
            "BROWSER_USE_AGE_KEYFILE=/run/secrets/age.key",
        ],
        "volumes": [
            "./config/browser_profiles:/config/browser_profiles",
            # NOTE: secrets/browser is mounted rw (not :ro) so the
            # entrypoint script can chown freshly-checked-out bind
            # mounts to the sidecar uid. See issue #143 and
            # docs/packs/browser_use-entrypoint.md for the rationale.
            "./config/secrets/browser:/config/secrets/browser",
            "./packs/browser_use:/opt/pack:ro",
        ],
        "secrets": [
            {"source": "age_key", "target": "age.key"},
        ],
        "deploy": {"resources": {"limits": {"memory": "2g"}}},
        # ``on-failure`` with a cap so a bad keyfile mount surfaces as a
        # quick crash + readable docker logs rather than an
        # ``unless-stopped`` infinite restart loop. The operator fixes
        # the mount, then ``docker compose --profile browser up -d``
        # brings it back.
        "restart": "on-failure:3",
    }


def _router_service(agent_names: list[str]) -> dict:
    env: list[str] = []
    for name in agent_names:
        prefix = name.upper()
        env.append(f"{prefix}_BOT_TOKEN=${{{prefix}_BOT_TOKEN}}")
        env.append(f"{prefix}_APP_TOKEN=${{{prefix}_APP_TOKEN}}")
        env.append(f"{prefix}_SIGNING_SECRET=${{{prefix}_SIGNING_SECRET}}")
    env.append("SESSION_TIMEOUT=${SESSION_TIMEOUT:-600}")
    env.append("LOG_LEVEL=${LOG_LEVEL:-DEBUG}")
    # Optional dev/prod-coexistence prefix for slash commands (e.g. ``dev-`` so
    # the dev deployment registers ``/dev-lisa-tasks`` while prod keeps
    # ``/lisa-tasks``). Without this passthrough, the variable lives only in
    # the host's ``.env`` and the container always sees an empty prefix.
    env.append("SLASH_COMMAND_PREFIX=${SLASH_COMMAND_PREFIX:-}")
    # /healthz port — consumed by the pull-based deploy daemon's health
    # probe (see scripts/deploy-pull.sh, issue #107). Default 8080.
    env.append("HEALTHZ_PORT=${HEALTHZ_PORT:-8080}")

    return {
        "build": {"context": ".", "dockerfile": "router/Dockerfile"},
        "environment": env,
        # Publish /healthz to the host so the deploy daemon (which runs
        # outside the container, on the systemd-managed host) can curl
        # http://localhost:8080/healthz after each restart.
        "ports": ["${HEALTHZ_PORT:-8080}:8080"],
        "volumes": [
            "/var/run/docker.sock:/var/run/docker.sock",
            "./config:/config",
            "./systems:/systems",
            "./packs:/app/packs:ro",
            "./data:/app/data",
        ],
        "deploy": {"resources": {"limits": {"memory": "256m"}}},
        "depends_on": list(agent_names),
        "restart": "unless-stopped",
    }


def _agent_service(name: str, manifest: dict, agents_dir: Path) -> dict:
    container = manifest.get("container", name)
    override_dockerfile = agents_dir / name / "Dockerfile"

    service: dict = {
        "container_name": container,
        "environment": [
            "CLAUDE_CODE_DISABLE_AUTO_MEMORY=1",
            "PATH=/opt/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        ],
        "volumes": [
            "./config:/config",
            "./systems:/systems",
            "./packs:/config/packs:ro",
            f"{name}-claude-config:/home/claude/.claude",
            "agent-tools:/opt/tools",
        ],
        "deploy": {"resources": {"limits": {"memory": "512m"}}},
        "restart": "unless-stopped",
    }

    if override_dockerfile.exists():
        try:
            dockerfile_rel = str(override_dockerfile.relative_to(REPO_ROOT))
        except ValueError:
            dockerfile_rel = str(override_dockerfile)
        service["build"] = {"context": ".", "dockerfile": dockerfile_rel}
    else:
        service["image"] = "ai-dev-team-base:latest"
        service["command"] = ["sleep", "infinity"]

    return service


def render(agents_dir: Path | None = None) -> str:
    """Return the rendered compose YAML (header + body)."""
    base = agents_dir if agents_dir is not None else DEFAULT_AGENTS_DIR
    agents = discover_agents(base)
    compose = build_compose(agents, base)
    body = yaml.safe_dump(compose, sort_keys=False, default_flow_style=False)
    return HEADER + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render docker-compose.yml from agent manifests.")
    parser.add_argument("--output", "-o", default=str(DEFAULT_OUTPUT), help="output path")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the file is stale")
    parser.add_argument(
        "--agents-dir",
        type=Path,
        default=None,
        help="agents dir to discover from (defaults to config/agents)",
    )
    args = parser.parse_args(argv)

    rendered = render(args.agents_dir)
    output_path = Path(args.output)

    if args.check:
        existing = output_path.read_text() if output_path.exists() else ""
        if existing != rendered:
            print(
                f"{output_path} is stale. Run 'python -m scripts.render_compose' to regenerate.",
                file=sys.stderr,
            )
            return 1
        print(f"{output_path} is up to date.")
        return 0

    output_path.write_text(rendered)
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
