"""Render ``docker-compose.yml`` from per-agent ``agent.yaml`` manifests.

The router service is fixed; per-agent services and the volumes / depends_on /
env-var lists are generated from the agents discovered under
``config/agents/*/agent.yaml``.

Usage:
    python -m scripts.render_compose                 # write docker-compose.yml
    python -m scripts.render_compose --check         # exit non-zero if stale
    python -m scripts.render_compose -o /tmp/foo.yml # write somewhere else

Default behaviour (no override Dockerfile present):
    services.<name>.image:   ai-dev-team-base:latest
    services.<name>.command: ["sleep", "infinity"]

Override: drop a ``Dockerfile`` next to the agent's manifest at
``config/agents/<name>/Dockerfile`` and the renderer switches that service
to ``build:`` instead.

Hand-edits go in ``docker-compose.override.yml`` (Compose's native escape
hatch); the renderer never touches it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from router.config import discover_agents

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "docker-compose.yml"
DEFAULT_AGENTS_DIR = REPO_ROOT / "config" / "agents"

HEADER = """\
# This file is GENERATED by scripts/render_compose.py from
# config/agents/*/agent.yaml manifests. Do not edit by hand — your changes
# will be overwritten the next time the renderer runs.
#
# Local-only tweaks should go in docker-compose.override.yml (Compose's
# native escape hatch), which the renderer never touches.

"""


def build_compose(agents: dict[str, dict], agents_dir: Path) -> dict:
    """Return the full docker-compose dict for the given agents."""
    sorted_names = sorted(agents.keys())

    services: dict[str, dict] = {"router": _router_service(sorted_names)}
    for name in sorted_names:
        services[name] = _agent_service(name, agents[name], agents_dir)

    # Opt-in browser_use sidecar. Gated by the ``browser`` compose
    # profile so default ``docker compose up`` skips it — the image is
    # heavy (Chromium + deps) and most agents don't need it.
    #
    # Hardcoded for now rather than discovered from pack manifests:
    # only one pack needs a sidecar today and the wiring (keyfile mount,
    # tmpfs, port, memory ceiling) isn't generic. When a second pack
    # asks for one we'll factor a ``packs/*/sidecar.yaml`` schema; see
    # the PR review thread on #113 for context.
    services["browser-use"] = _browser_use_sidecar()

    volumes: dict[str, None] = {f"{name}-claude-config": None for name in sorted_names}
    # Shared volume for on-demand CLI binaries (gh, fly, …) installed via
    # scripts/install_cli.sh. Mounted into every agent at /opt/tools so new
    # tools become available without rebuilding the base image.
    volumes["agent-tools"] = None
    # Dispatch workspaces are a host bind-mount (not a named volume) so the
    # autodeploy drain helper running on the host can read state files at the
    # same fixed path.  Named-volume data lives under
    # /var/lib/docker/volumes/… which the host cannot read without root and
    # an opaque internal path — that made the drain a no-op in prod (#339).

    return {"services": services, "volumes": volumes, "secrets": _secrets_block()}


def _secrets_block() -> dict:
    """Top-level ``secrets:`` block. Currently only the browser_use age keyfile.

    ``AGE_KEYFILE`` is the same env var the bootstrap script honours, so a
    one-shot override (``AGE_KEYFILE=~/.config/ai-dev-team/age.key``) flows
    through both bootstrap and compose without divergence. Default
    ``/etc/ai-dev-team/age.key`` matches a Linux prod host; macOS dev needs
    a path under ``~`` because Docker Desktop's file sharing excludes
    ``/etc`` by default — see ``packs/browser_use/README.md``.
    """
    return {
        "age_key": {"file": "${AGE_KEYFILE:-/etc/ai-dev-team/age.key}"},
    }


def _browser_use_sidecar() -> dict:
    """Compose entry for the browser_use sidecar.

    Mounts:
    - ``./config/browser_profiles`` rw — persistent per-identity Chromium
      profile dirs. Survives sidecar restarts so logins stick.
    - ``./config/secrets/browser`` ro — age-encrypted secret bundle.
      Decrypted in memory at session start; never written to disk in
      plaintext.
    - The host age keyfile arrives via the top-level ``secrets:`` block
      and lands at ``/run/secrets/age.key`` inside the container. Host
      path is ``${AGE_KEYFILE:-/etc/ai-dev-team/age.key}`` — same env
      var the bootstrap script reads.

    Network: the sidecar listens on the docker network only — no host
    port binding. The pack handler reaches it at ``http://browser-use:8080``.
    """
    return {
        "container_name": "browser-use",
        "profiles": ["browser"],
        "build": {"context": ".", "dockerfile": "docker/Dockerfile.browser"},
        "environment": [
            "BROWSER_USE_PROFILES_DIR=/config/browser_profiles",
            "BROWSER_USE_SECRETS_DIR=/config/secrets/browser",
            "BROWSER_USE_AGE_KEYFILE=/run/secrets/age.key",
        ],
        "volumes": [
            "./config/browser_profiles:/config/browser_profiles",
            # NOTE: secrets/browser is mounted rw (not :ro) so the
            # entrypoint script can chown freshly-checked-out bind
            # mounts to the sidecar uid. See issue #143 and
            # docs/packs/browser_use-entrypoint.md for the rationale.
            "./config/secrets/browser:/config/secrets/browser",
            "./packs/browser_use:/opt/pack:ro",
        ],
        "secrets": [
            {"source": "age_key", "target": "age.key"},
        ],
        "deploy": {"resources": {"limits": {"memory": "2g"}}},
        # ``on-failure`` with a cap so a bad keyfile mount surfaces as a
        # quick crash + readable docker logs rather than an
        # ``unless-stopped`` infinite restart loop. The operator fixes
        # the mount, then ``docker compose --profile browser up -d``
        # brings it back.
        "restart": "on-failure:3",
    }


def _router_service(agent_names: list[str]) -> dict:
    env: list[str] = []
    for name in agent_names:
        prefix = name.upper()
        env.append(f"{prefix}_BOT_TOKEN=${{{prefix}_BOT_TOKEN}}")
        env.append(f"{prefix}_APP_TOKEN=${{{prefix}_APP_TOKEN}}")
        env.append(f"{prefix}_SIGNING_SECRET=${{{prefix}_SIGNING_SECRET}}")
        # Discord backend creds (#641/#643). The manifest's backends.discord
        # block resolves ``${SECRET:<AGENT>_DISCORD_BOT_TOKEN}`` /
        # ``_CHANNEL_ID`` against the router container's environment
        # (router/config.py resolve_secret_ref, fail-loud on missing). Without
        # this passthrough the secrets live only in the host .env and the
        # container sees them unset — so the moment DISCORD_ENABLED is flipped
        # on, config.build_discord_credentials raises ValueError at boot. Same
        # #355 deploy-host-drift rationale as the flags below: keep the wiring
        # in committed source, never as an uncommitted docker-compose.yml edit.
        env.append(f"{prefix}_DISCORD_BOT_TOKEN=${{{prefix}_DISCORD_BOT_TOKEN}}")
        env.append(f"{prefix}_DISCORD_CHANNEL_ID=${{{prefix}_DISCORD_CHANNEL_ID}}")
    # Worker outbound-post identities. WORKERS_BOT_TOKEN posts worker status back
    # to Slack; WORKERS_DISCORD_TOKEN does the same for Discord-origin dispatches
    # (#665). Both are forwarded from the host .env so an operator only edits .env
    # — never patches a token into a committed file. Empty default (``:-``) is
    # falsy, so dispatch_hook / app.py fall back to the secrets.json entry when
    # the var is unset: zero regression for store-configured deploys.
    env.append("WORKERS_BOT_TOKEN=${WORKERS_BOT_TOKEN:-}")
    env.append("WORKERS_DISCORD_TOKEN=${WORKERS_DISCORD_TOKEN:-}")
    env.append("SESSION_TIMEOUT=${SESSION_TIMEOUT:-600}")
    env.append("LOG_LEVEL=${LOG_LEVEL:-DEBUG}")
    # Optional dev/prod-coexistence prefix for slash commands (e.g. ``dev-`` so
    # the dev deployment registers ``/dev-lisa-tasks`` while prod keeps
    # ``/lisa-tasks``). Without this passthrough, the variable lives only in
    # the host's ``.env`` and the container always sees an empty prefix.
    env.append("SLASH_COMMAND_PREFIX=${SLASH_COMMAND_PREFIX:-}")
    env.append("WORKER_MENTION_HANDOFF=${WORKER_MENTION_HANDOFF:-0}")
    # Dispatch milestone feed (#338): on by default for every deploy. Kept as a
    # passthrough so an operator can still disable it via .env
    # (DISPATCH_MILESTONE_FEED=0) without a code change. Previously this flag was
    # carried only as an uncommitted host edit on docker-compose.yml, which the
    # next clean deploy silently dropped — see the #355 deploy-host-drift incident.
    env.append("DISPATCH_MILESTONE_FEED=${DISPATCH_MILESTONE_FEED:-1}")
    # Attachments ingest (#325/#327): on by default for every deploy. Same
    # passthrough rationale as the milestone feed above — an operator can still
    # disable it via .env (ATTACHMENTS_ENABLED=0) without a code change, and the
    # flag lives in committed config rather than as an uncommitted host edit that
    # the next clean deploy would silently drop (#355 deploy-host-drift incident).
    env.append("ATTACHMENTS_ENABLED=${ATTACHMENTS_ENABLED:-1}")
    # Global Discord master switch (#641/#643). app.py gates the entire Discord
    # adapter build on this — unset/false leaves the Slack path untouched. Opt-in
    # per deployment (no default), passthrough so it lives in .env like the other
    # feature flags rather than as an uncommitted host edit (#355 drift).
    env.append("DISCORD_ENABLED=${DISCORD_ENABLED:-}")
    # Idle auto-merge queue (#437): the router registers the idle-automerge
    # system task only when MERGE_QUEUE_REPO is set. Passthrough with no default
    # so the feature is opt-in per deployment — the repo/account is operator
    # config (set MERGE_QUEUE_REPO=<owner>/<repo> in .env), never baked into the
    # committed source, which keeps the codebase portable (single-dir copy works
    # for any account). The queue is NOT a blind merger: a PR only merges when it
    # has a non-author approving review OR the ``auto-merge`` label AND required
    # checks are green AND the system has been idle 10min (router/merge_queue.py
    # is_system_idle) — the per-PR approval gate is the circuit breaker.
    env.append("MERGE_QUEUE_REPO=${MERGE_QUEUE_REPO:-}")
    # Slack destination for merge-queue merge/error notices. Dedicated, generically
    # named var (NOT the per-operator BRAM_DM_CHANNEL fallback) so merge-queue
    # notices can target a CI/CD channel without redirecting every other scheduled
    # task's fallback destination. Deployment-specific channel id, so it lives in
    # .env like a credential rather than baked in code. Without it the merge queue
    # still merges but posts nothing — auto-merges go silent, which defeats the
    # circuit-breaker's visibility leg; set it in .env for walk-away.
    env.append("MERGE_QUEUE_CHANNEL=${MERGE_QUEUE_CHANNEL:-}")
    # Slack destination for the autonomous bug-backlog loop's dispatch / shadow
    # (dry-run) notices (#535, router/app.py auto-dispatch tick). Same rationale
    # as MERGE_QUEUE_CHANNEL above: dedicated, generically named var so the loop
    # can target a CI/CD channel without hijacking BRAM_DM_CHANNEL's per-operator
    # fallback. Deployment-specific channel id, so it lives in .env like a
    # credential rather than baked in code. Resolution order in app.py is
    # AUTO_DISPATCH_CHANNEL -> BRAM_DM_CHANNEL -> None; without it the loop falls
    # back to the operator DM. Set AUTO_DISPATCH_CHANNEL=<channel-id> in .env to
    # land these (incl. shadow-mode ghost lines) in the CI/CD channel.
    env.append("AUTO_DISPATCH_CHANNEL=${AUTO_DISPATCH_CHANNEL:-}")
    # Backlog repo for the autonomous bug-backlog loop (#535/#536). Same opt-in
    # passthrough shape as MERGE_QUEUE_REPO above: the router only registers the
    # auto-dispatch tick when AUTO_DISPATCH_REPO is set, otherwise it logs
    # "AUTO_DISPATCH_REPO not set; skipping ..." and the loop never runs. No
    # default so the feature is opt-in per deployment and the repo/account stays
    # operator config in .env rather than baked into the portable source. Set
    # AUTO_DISPATCH_REPO=<owner>/<repo> in .env to arm the loop (ships shadow-ON,
    # kill-switch-OFF, so it dry-runs to AUTO_DISPATCH_CHANNEL first).
    env.append("AUTO_DISPATCH_REPO=${AUTO_DISPATCH_REPO:-}")
    # Shared bearer token for the compose-internal dispatch API (port 8090).
    # Required — router fail-fasts at startup if this var is absent.
    env.append("ROUTER_INTERNAL_TOKEN=${ROUTER_INTERNAL_TOKEN}")
    # /healthz is hardcoded to 8080 inside the container; the host-side
    # port is overridable via HEALTHZ_PORT (see the ``ports:`` mapping
    # below). We deliberately do NOT pass HEALTHZ_PORT into the container
    # — earlier wiring let the router rebind to the override, which
    # broke the host→container forward when the two diverged.

    volumes = [
        "/var/run/docker.sock:/var/run/docker.sock",
        "./config:/config",
        "./systems:/systems",
        "./packs:/app/packs:ro",
        "./data:/app/data",
    ]
    # Mount the dispatch bind-mount into the router r/w so the
    # supervision callable (see router/dispatch/supervision.py) can
    # read state files and write synthetic exitcode / halt_marker on
    # timeout, kill, and orphan detection. Only needed when Sam (the
    # owner of the workspace) exists. Path is repo-relative (./var/dispatch)
    # so the whole stack travels with a single directory copy (#339 contract).
    if "sam" in agent_names:
        volumes.append("./var/dispatch:/var/lib/dispatch")

    # #327: Attachments shared scratch dir — router gets rw access so it can
    # create per-thread subdirs and touch them on every message.
    volumes.append("/var/lib/attachments:/var/lib/attachments")

    return {
        "build": {"context": ".", "dockerfile": "router/Dockerfile"},
        "environment": env,
        # Publish /healthz to loopback only — the deploy daemon runs on
        # the same host and curls 127.0.0.1, so there is no reason to
        # expose the probe to other interfaces. HEALTHZ_PORT selects the
        # *host* side; the container side is always 8080.
        "ports": ["127.0.0.1:${HEALTHZ_PORT:-8080}:8080"],
        "volumes": volumes,
        "deploy": {"resources": {"limits": {"memory": "256m"}}},
        "depends_on": list(agent_names),
        "restart": "unless-stopped",
    }


def _agent_service(name: str, manifest: dict, agents_dir: Path) -> dict:
    container = manifest.get("container", name)
    override_dockerfile = agents_dir / name / "Dockerfile"

    service: dict = {
        "container_name": container,
        "environment": [
            "CLAUDE_CODE_DISABLE_AUTO_MEMORY=1",
            "PATH=/opt/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "PYTHONPATH=/opt/router_shared",
            # Shared bearer token for dispatch.draft → router internal API calls.
            "ROUTER_INTERNAL_TOKEN=${ROUTER_INTERNAL_TOKEN}",
        ],
        "volumes": [
            "./config:/config",
            "./systems:/systems",
            "./packs:/config/packs:ro",
            f"{name}-claude-config:/home/claude/.claude",
            "agent-tools:/opt/tools",
            "./router/scheduled_tasks:/opt/router_shared/router/scheduled_tasks:ro",
        ],
        "deploy": {"resources": {"limits": {"memory": "512m"}}},
        "restart": "unless-stopped",
    }

    if name == "sam":
        # Repo-relative bind-mount for the dispatch pack (packs/dispatch/).
        # Holds per-dispatch workspaces at /var/lib/dispatch/<dispatch_id>/.
        # Bind-mount (not named volume) so the autodeploy drain helper on
        # the host can read the same path; repo-relative (./var/dispatch) so
        # the stack stays single-dir-copy portable — see issue #339.
        service["volumes"].append("./var/dispatch:/var/lib/dispatch")

    # #327: Attachments shared scratch dir — named agents get read-only access
    # so they can read attachments deposited by the router or ingest packs.
    # Workers have no mount (out of scope for this issue).
    service["volumes"].append("/var/lib/attachments:/var/lib/attachments:ro")

    if override_dockerfile.exists():
        try:
            dockerfile_rel = str(override_dockerfile.relative_to(REPO_ROOT))
        except ValueError:
            dockerfile_rel = str(override_dockerfile)
        service["build"] = {"context": ".", "dockerfile": dockerfile_rel}
    else:
        service["image"] = "ai-dev-team-base:latest"
        service["command"] = ["sleep", "infinity"]

    return service


def render(agents_dir: Path | None = None) -> str:
    """Return the rendered compose YAML (header + body)."""
    base = agents_dir if agents_dir is not None else DEFAULT_AGENTS_DIR
    agents = discover_agents(base)
    compose = build_compose(agents, base)
    body = yaml.safe_dump(compose, sort_keys=False, default_flow_style=False)
    return HEADER + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render docker-compose.yml from agent manifests.")
    parser.add_argument("--output", "-o", default=str(DEFAULT_OUTPUT), help="output path")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the file is stale")
    parser.add_argument(
        "--agents-dir",
        type=Path,
        default=None,
        help="agents dir to discover from (defaults to config/agents)",
    )
    args = parser.parse_args(argv)

    rendered = render(args.agents_dir)
    output_path = Path(args.output)

    if args.check:
        existing = output_path.read_text() if output_path.exists() else ""
        if existing != rendered:
            print(
                f"{output_path} is stale. Run 'python -m scripts.render_compose' to regenerate.",
                file=sys.stderr,
            )
            return 1
        print(f"{output_path} is up to date.")
        return 0

    output_path.write_text(rendered)
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
